In [1]:
from functions import *

In [2]:
a = np.array([2.3, 4.5, -1.2, 0.8])
b = np.array([1.4, -0.2, 6.7, 4.8])

sbx(a, b, u=0.42, nc=2)

(array([ 2.27459246,  4.36731617, -0.97697824,  0.91292241]),
 array([ 1.42540754, -0.06731617,  6.47697824,  4.68707759]))

In [14]:
0.5 * ((a+b) - beta * (b-a))

array([ 2.27459246,  4.36731617, -0.97697824,  0.91292241])

In [15]:
0.5 * ((a+b) + beta * (b-a))

array([ 1.42540754, -0.06731617,  6.47697824,  4.68707759])

In [2]:
y = initialize(1, True)

5.819064884344019
158190


In [5]:
population = []
for i in range(2):
    population.append(initialize(2,True,constraints=[(-2.048,2.048),(-2.048,2.048)]))

-0.47716437819644586
15708
0.7181618832580967
27661
-1.8045403987651403
2434
-0.20724664624243494
18407


In [9]:
population[1][1]

'0100011111100111'

In [10]:
population[0][1]

'0110110000001101'

In [16]:
point_crossover(population[1][1],population[0][1],4)

[11, 5, 9, 8]


('01000111111111111100111', '01101100000100000001101')

In [5]:
roulete_wheel(population,f_A, False)

[193.47113904 556.25335361 534.18844872 196.73982754   0.        ]
[0.13066611 0.50634727 0.86712629 1.         1.        ]
0.7605283121271361


array([0.45212803, 0.67520955])

In [11]:
tournament_selection(population,f_A, False)

[193.47113904 556.25335361 534.18844872 196.73982754   0.        ]
[2 3 0 4 1]


array([2, 0, 1])