In [1]:
from ga import *

In [2]:
a = True and True
print(a)

True


In [3]:
avg, std, max = ga_solve(200, True, f_A, [(-2.048, 2.048),(-2.048, 2.048)],True, 2)

In [4]:
def obj_func_numpy(x):
    f_A_lambdified = sp.lambdify((sp.symbols('x1'), sp.symbols('x2')), f_A, 'numpy')
    return f_A_lambdified(x[0], x[1])

# Define bounds for the differential evolution
bounds = [(-2.048, 2.048),(-2.048, 2.048)]

from scipy.optimize import differential_evolution

# Run the differential evolution algorithm
result = differential_evolution(obj_func_numpy, bounds)

In [6]:
print(f"True minimum found by differential evolution at x1 = {result.x[0]:.2f}, x2 = {result.x[1]:.2f}, with value = {result.fun:.2f}")

True minimum found by differential evolution at x1 = 1.00, x2 = 1.00, with value = 0.00


In [4]:
avg

[3901.426932325814, 3900.362781869678]

In [5]:
std

[2.2801099757888483,
 2.2023964568897534,
 2.000972895799786,
 1.7473110338484423,
 1.3446561060251196,
 0.9778764485713424,
 0.9188328039830862,
 0.767903471992425,
 0.6924398932161622,
 0.5894907054886864]

In [3]:
a = []
b = []
for i in range(200):
    individual, prueba = initialize(2, True, constraints=[(-2.048, 2.048),(-2.048, 2.048)]) # np.arrays
    a.append(individual)
    b.append(prueba)

In [4]:
c = decode_population(a,[(-2.048, 2.048),(-2.048, 2.048)])

In [6]:
b

[array([-0.02186521,  0.69682589]),
 array([-0.49590117, -1.31963707]),
 array([ 0.94493789, -0.01186695]),
 array([ 1.69560735, -0.33848173]),
 array([-1.58668343,  2.02209922]),
 array([-1.93021516, -0.09459689]),
 array([ 1.67611176, -0.97574085]),
 array([ 1.89060225, -1.43111266]),
 array([-0.58568389, -0.23175636]),
 array([-0.76539582,  1.37299409]),
 array([-1.95409824, -0.38200591]),
 array([ 1.06438913, -1.94926826]),
 array([ 1.83315148, -0.77737968]),
 array([-1.83445584,  0.76237557]),
 array([ 1.9124468, -1.3529093]),
 array([0.63877786, 1.02557317]),
 array([0.41866419, 1.94427643]),
 array([-1.92802912, -1.43139359]),
 array([ 0.5648039 , -0.36895095]),
 array([-1.89365012,  1.80448611]),
 array([-1.70718987,  0.8375678 ]),
 array([-1.50025872,  0.18902852]),
 array([1.93699073, 0.96308599]),
 array([-1.09705535, -1.32969328]),
 array([ 1.44666989, -0.2236291 ]),
 array([ 1.21811596, -1.5699575 ]),
 array([ 1.30511529, -1.6055229 ]),
 array([0.21614656, 0.3708459 ]),
 a

In [5]:
c

array([[-2.0473, -2.047 ],
       [-2.0475, -2.0478],
       [-2.047 , -2.0473],
       [-2.0467, -2.0474],
       [-2.0479, -2.0466],
       [-2.048 , -2.0473],
       [-2.0467, -2.0477],
       [-2.0466, -2.0478],
       [-2.0475, -2.0474],
       [-2.0476, -2.0468],
       [-2.048 , -2.0474],
       [-2.0469, -2.048 ],
       [-2.0466, -2.0476],
       [-2.048 , -2.047 ],
       [-2.0466, -2.0478],
       [-2.0471, -2.0469],
       [-2.0471, -2.0466],
       [-2.048 , -2.0478],
       [-2.0471, -2.0474],
       [-2.048 , -2.0466],
       [-2.0479, -2.047 ],
       [-2.0478, -2.0472],
       [-2.0466, -2.0469],
       [-2.0477, -2.0478],
       [-2.0468, -2.0474],
       [-2.0469, -2.0479],
       [-2.0468, -2.0479],
       [-2.0472, -2.0472],
       [-2.0469, -2.0477],
       [-2.0475, -2.0479],
       [-2.0472, -2.0478],
       [-2.0478, -2.047 ],
       [-2.0468, -2.0478],
       [-2.0472, -2.0471],
       [-2.0469, -2.0474],
       [-2.0468, -2.0466],
       [-2.0466, -2.0477],
 

In [25]:
np.max(b)

-2.0466

In [19]:
decode_binary('1010',(-2.048, 2.048))

-2.047

In [21]:
decode_binary('1110',(-2.048, 2.048))

-2.0466

In [8]:
np.mean(eval_population(a,f_A,True, [(-2.048, 2.048),(-2.048, 2.048)]))

3901.2564651453217

In [6]:
max

[3897.0182098232835,
 3897.0059906325055,
 3896.8812883875053,
 3896.3824994075067,
 3896.507193652505,
 3896.3824994075067,
 3896.3824994075067,
 3896.3824994075067,
 3896.3824994075067,
 3896.3824994075067]